name: Build and Push Jupyter Superslim with R Image

on:
  push:
    paths:
      - jupyter-superslim-rkernel/**
      - .github/workflows/build_and_push_jupyter_superslim_rkernel.yml
  pull_request:
    types: [opened, reopened]
    paths:
      - jupyter-superslim-rkernel/**
      - .github/workflows/build_and_push_jupyter_superslim_rkernel.yml

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  build_superslim_r_image:
    name: Build Image and Push (jupyter-superslim-r)
    uses: uc-cdis/.github/.github/workflows/image_build_push_native.yaml@master
    with:
      DOCKERFILE_LOCATION: "./jupyter-superslim-rkernel/Dockerfile"
      DOCKERFILE_BUILD_CONTEXT: "./jupyter-superslim-rkernel"
      OVERRIDE_REPO_NAME: "jupyter-superslim-r"
      USE_QUAY_ONLY: true
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
